name = "biblio-ia-vectorize"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[vectorize]]
binding = "VECTORIZE"
index_name = "biblio-ia-embeddings"

[[kv_namespaces]]
binding = "BIBLIO_KV"
id = "104b779c7e1d459d88fac47928090b20"
